version: '3'
services:
  mysql_test:
    image: mysql 
    restart: always
    #tty: true
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      
  api_test:
    build:
     context: ./mysql
     dockerfile: Dockerfile
    
    volumes:
     - ./src:/go/src
    
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=Root
    ports:
      - "8080:8080"
  
